background_opacity 0.9

window_padding_width 10.0

# === Управление (Hotkeys) ===

# Отключаем стандартные звуки ("бип")

enable_audio_bell no

font_size 12.0
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font autoinactive_text_alpha 0.6


# Копирование и вставка (как в браузере)

map ctrl+shift+c copy_to_clipboard

map ctrl+shift+v paste_from_clipboard


# Быстрый релоад конфига без перезапуска терминала

map ctrl+shift+f5 load_config_file 


include themes/noctalia.conf
